# The IBM version of this configuration
version : 0.0.3

# The container name used for the run container
container-name-run : "springbootcrudrepositoryexample"

# The container name used for the tools container
container-name-tools : "bx-dev-springbootcrudrepositoryexample-tools"

# The name of image to create from dockerfile-run
image-name-run : "springbootcrudrepositoryexample"

# The project root in the run container to mount to host-path-run
container-path-run : "/project"
# The project root in the tools container that will be mounted to host-path-tools
container-path-tools : "/project"

# The port mappings between the host and the container in the form [host:container]
container-port-map : "8080:8080,8443:8443"
# The port mappings between the host and the container for the debug port in the form [host:container]
container-port-map-debug : "8000:8000"

# The command to execute debug of the code in the tools container
debug-cmd : "java -Dspring.profiles.active=local -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=y -jar springbootcrudrepositoryexample-.jar"

# The name for the dockerfile for the run container
dockerfile-run : "Dockerfile"

# The name for the dockerfile for the tools container
dockerfile-tools : "Dockerfile-tools"

# The relative path to the helm chart used for Kubernetes deployment
chart-path : "chart/springbootcrudrepositoryexample"
